name: Share data between jobs
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: yarn
      - name: Run build
        run: |
          yarn build
          cp build/index.html ${{ github.workspace }}/
      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: buildfile
          path: ${{ github.workspace }}/index.html

  job_2:
    name: Copy build file
    needs: job_1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download build file for job 1
        uses: actions/download-artifact@v2
        with:
          name: buildfile
          path: ${{ github.workspace }}
      - name: Display structure of downloaded files
        run: |
          ls
          cat index.html
      - name: Use cp-action
        uses: devevignesh/cp-to-repo@v9
        with:
          api-token-github: ${{ secrets.GIT_API_TOKEN }}
          source-file: index.html
          destination-github-username: 'devevignesh'
          destination-repository-name: 'react-hooks'
          user-email: vigneshe1992@gmail.com
