name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  job_1:
    name: Build 
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: yarn
      - name: Run build
        run: |
          yarn build
          cp -R build/ ${{ github.workspace }}/static/
          
  job_2:
    name: Deploy
    needs: job_1
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Push static files
        run: |
          cd ${{ github.workspace }}
          ls
