name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  job_1:
    name: Build 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn
      - name: Run build
        run: |
          yarn build
          cp -R build/ ${{ github.workspace }}/buildFiles/
      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: Build
          path: ${{ github.workspace }}/buildFiles/
  job_2:
    name: Deploy
    needs: job_1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: Build
      - name: Push static files
        run: |
          TEMP_DIR=$(mktemp -d)
          TARGET_BRANCH="release-build"
          echo "Cloning destination git repository"
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name "devevignesh"
          git clone -n "https://devevignesh:${{ secrets.GIT_API_TOKEN }}@github.com/devevignesh/react-hooks.git" --depth 1 "$TEMP_DIR"
          cd "$TEMP_DIR"
          git reset HEAD
          git checkout HEAD "static"
          cp -R ${{ github.workspace }}/buildFiles/ "$TEMP_DIR"/.
          echo "Files that will be pushed"
          ls
