name: Add a comment
on: 
  pull_request:
    types: [closed]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: devevignesh/git-asana-action@v3
        if: github.event.pull_request.merged == true
        with:
          asana-pat: ${{ secrets.ASANA_PAT }}
          task-comment: 'PR: '
          trigger-phrase: 'Asana Task:'
