name: Share data between jobs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: yarn
      - name: Run build
        run: |
          yarn build
          mkdir -p ${{ github.workspace }}
          cp build/index.html ${{ github.workspace }}/
      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: buildfile
          path: ${{ github.workspace }}/index.html
