name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  job_1:
    name: Build 
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: yarn
      - name: Run build
        run: |
          yarn build
          cp -R build/ ${{ github.workspace }}/static/
      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: Build
          path: ${{ github.workspace }}/static/
        
          
  job_2:
    name: Deploy
    needs: job_1
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: Build
      - name: Push static files
        run: |
          TEMP_DIR=$(mktemp -d)
          TARGET_BRANCH="release-build"
          echo "Cloning destination git repository"
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name "devevignesh"
          git clone -n "https://devevignesh:${{ secrets.GIT_API_TOKEN }}@github.com/devevignesh/react-hooks.git" --depth 1 "$TEMP_DIR"
          cd "$TEMP_DIR"
          git reset HEAD
          git checkout HEAD "static"
          cp -R ${{ github.workspace }}/static/ "$TEMP_DIR"/src/.
          echo "Files that will be pushed"
          git add src/*
          git checkout -b "$TARGET_BRANCH"
          git status
          echo "git commit"
          git commit -m "static files"
          echo "git push origin"
          git push "https://devevignesh:${{ secrets.GIT_API_TOKEN }}@github.com/devevignesh/react-hooks.git" --set-upstream
          echo "success"
