name: Build and Deploy
on:
  push:
    branches:
        [main]
jobs:
  job_1:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: github tag
        run: |
          echo "client:${{ github.event.release.tag_name }}"
