name: Build and Deploy
on:
  push:
    branches:
        [main]
jobs:
  job_1:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: yarn
      - name: Run build
        run: |
          yarn build
      - name: Upload build files to S3
        uses: devevignesh/S3-deploy-gh-action@v1.0.2
        with:
         release-tag-name: "v1.0.2"
         source-dir: "build"
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
