name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: yarn
      - name: Run build
        run: yarn build
      - name: Use cp-action
        uses: devevignesh/cp-to-repo@v5
        with:
          api-token-github: ${{ secrets.GIT_API_TOKEN }}
          source-directory: 'build/index.html'
          destination-github-username: 'devevignesh'
          destination-repository-name: 'react-hooks'
          user-email: vigneshe1992@gmail.com
